import { Inter } from "next/font/google";
import Header from "@/components/Header/Header";
import SideBar from "@/components/Secretaire/SideBar/SideBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children}) {

  return (
    <html lang="en">
       <body className="w-full h-screen bg-blue-100">
        <div className="w-[100%] flex flex-row">
          <div className="w-[13.5%]">
           <SideBar/>
          </div>
          <div className="w-[90%] h-screen">
            <Header/>
            <div className="w-[100%] h-[59%] rounded-md overflow-y-auto">
              {children}
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
